### ISSUE TITLE
Only working for close, not for minimize

### ISSUE THREAD

**Issue by Pryrios** [nmaier/mintrayr#103]
I'm under Linux Mint 14 with Cinnamon, TB version 17.

I have the addon configured for minimizing on closing and on minimize, but it only minimizes to tray if I close. If I just minimize it stays on task bar as without the addon.

I've tried with close only an minimize only configurations and works the same, just minimizing to tray on close only option and staying minimized on task bar on minimize only.

¿Perhaps the problem is Cinnamon?

**Comment by sboekhoff** [comment]
Same problem using `Linux Mint 18 Cinnamon 64-bit`

Cinnamon Version: `3.0.7`

Thunderbird Version: `45.4.0`
