### ISSUE TITLE
Console errors

### ISSUE THREAD

**Issue by crazy-max** [nmaier/mintrayr#139]
Hi,

Windows 8.1 64-bits
Thunderbird 38.0.1
MinimizeToTray revived (MinTrayR) 1.1.2.1-signed

I have check my thunderbird console et saw some errors relative to your plugin :

![console](https://cloud.githubusercontent.com/assets/1951866/8148361/bfd56bb2-1299-11e5-8735-b9830e2e57a8.jpg)

**Comment by CassandraDied** [comment]
Confirm.
Win 8.1, x64.

Error: Failed to clone newNewMsgCmd
Source File: resource://mintrayr/mintrayr.jsm
Line: 124

Thunderbird does not check for new mails.

**Comment by crazy-max** [comment]
Thx!
