### ISSUE TITLE
Add "hidden" tray icon with hotkey to show main window.

### ISSUE THREAD

**Issue by BladeMight** [nmaier/mintrayr#152]
I would really like a hidden tray feature, and a hotkey to show main window. I have not seen any mail agent that can work silent/background(except W10 Mail, but i don't like it), as for firefox if you start it with this hidden mode it will start ligtningly fast! So what you think about it? Can you make this?

**Comment by nmaier** [comment]
That would require a global hotkey, meaning a global keyboard "listener", and those are pretty restricted in Windows and pretty bug prone on top of that, so now, I won't be making this feature myself.

**Comment by BladeMight** [comment]
Too bad -_-

**Comment by ghost** [comment]
It's a pity! -_-
