### ISSUE TITLE
Cannot restore Thunderbird window when Show Always not enabled

### ISSUE THREAD

**Issue by tbertels** [nmaier/mintrayr#156]
With Thunderbird 45.2.0 and Windows 7 SP1 64 bits and MinTrayR 1.3.1, the main Thunderbird window can't be restored if Show Always isn't enabled.
Clicking on the MinTrayR doesn't do anything, same thing for the Restore command in the context menu.
The only way to restore the Thunderbird window is then to open again Thunderbird.

With Show Always enabled, once we open a Write window, a second icon gets into the notification area and stays there until we close Thunderbird. It has the name of the Write window.

**Comment by dailysmart** [comment]
Confirm that behavior too, except 

> The only way to restore the Thunderbird window is then to open again Thunderbird.

Actually "Restore all" in tray icon context menu works always, regardless of Tray-Icon option "Show always" checked or not.

**Comment by RDL-github** [comment]
>  tbertels commented

> With Thunderbird 45.2.0 and Windows 7 SP1 64 bits and MinTrayR 1.3.1, the main Thunderbird window can't be restored if Show Always isn't enabled.
> Clicking on the MinTrayR doesn't do anything,

Same for me with MinTrayR 1.3.1 in **Firefox** 47.0.1 x64 on Win 10 x64

If Show Always isn't enabled, then, when window titlebar Minimise is clicked, FF minimises to tray as expected but won't then restore if the icon is clicked.

It works if Show Always is enabled but setting that doesn't suit my use.

I ended up killing FF and re-running it.

Retreated to MinTrayR 1.1.2.1-signed.1-signed which still works well.

Regards

RDL

**Comment by nmaier** [comment]
I cannot reproduce this so far, tried Thunderbird, and Firefox x64 myself...
Any further pointers would be appreciated

**Comment by nmaier** [comment]
Oh wait, nvm, can reproduce it now when the full Aero experience is enabled. Hmmm
