### ISSUE TITLE
Since FireFox 48, it won't restore FireFox unless icon is set to "always show"

### ISSUE THREAD

**Issue by Kyliathy** [nmaier/mintrayr#157]
As the title says :), regardless if the icon is set to show FireFox on single or double click, it doesn't work. UNLESS it's set to be always visible in the tray. Then, it works ;). It's good I discovered that so at least I can continue to use this wonderful addon. Fix this and I'm donating :D.

**Comment by nmaier** [comment]
#156

**Comment by Kyliathy** [comment]
Thank you. Donated :D.
