### ISSUE TITLE
Stopped working with Thunderbird 52.0

### ISSUE THREAD

**Issue by Bachsau** [nmaier/mintrayr#175]
With Thunderbird 52.0 on Linux MinTrayR stopped working completely. Can you fix it?

**Comment by Bachsau** [comment]
Tracked it down to a function that "hijacks" buttons instead of attaching to window actions. However, I don't know enough about Thunderbird to fix it. Unfortunately it seems @nmaier abandoned this addon.

**Comment by jelhan** [comment]
I could confirm that minimize to tray instead of closing stopped working in Thunderbird 52.1.1 on Gnome 3. The other features still seem to work fine.

**Comment by jelhan** [comment]
This seems to be a duplicate of #172.

**Comment by SergeyLatyshev** [comment]
It stopped working for me on Lubuntu and Linux Mint Cinnamon. The Windows version works fine.

**Comment by Bachsau** [comment]
Closed because of mintrayr being unmaintained.

**Comment by qwertychouskie** [comment]
@Bachsau Addon is maintained at https://github.com/ysard/mintrayr / https://addons.thunderbird.net/en-US/thunderbird/addon/minimizetotray-reanimated/
