### ISSUE TITLE
Can you please update to Thunderbird 60

### ISSUE THREAD

**Issue by TheBudda** [nmaier/mintrayr#189]
This is a great add-on for Thunderbird. I have used it for years. I do NOT understand Mozilla with these add-ons. Developers/People go out of there way to make them, then Mozilla changes the code and it causes a nightmare for people using these add-ons. Mozilla should show developers more respect! Mozilla should make future updates to the old add-on so they are useable!

 Can you please upgrade this add-on to work with Thunderbird 60+ I look forward to your reply

Kind regards
Budda

**Comment by Croydon** [comment]
Duplicate.

Please use the search first.

https://github.com/nmaier/mintrayr/issues/188

**Comment by TheBudda** [comment]
LOL!! Very nice attitude!! I give the developer a big up on this add-on and a big down to Mozilla! You come along and dust me down!! Thanks for that I really appreciate your harsh reply. I won't ask again

**Comment by Croydon** [comment]
I'm sorry if you think my reply is harsh. I do encounter duplicate issues almost daily so I won't write every time an entire paragraph of text when it can be noted faster.

Duplicate issues distract people from having an overview over tasks which should get done and is splitting the discussion over several places.

Feel free to re-post your opinion in the already existing issue. Also note that I'm not involved in this project.
